import http from "http";
import { readFile } from "fs/promises";
import { extname, join, resolve } from "path";

const root = resolve(".");
const publicDir = join(root, "public");
const port = Number(process.env.PORT || 3000);
const openAiKey = process.env.OPENAI_API_KEY || "";

const MIME_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".svg": "image/svg+xml"
};

async function parseJsonBody(req) {
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString("utf8");
  return raw ? JSON.parse(raw) : {};
}

function sendJson(res, code, payload) {
  res.writeHead(code, { "Content-Type": "application/json; charset=utf-8" });
  res.end(JSON.stringify(payload));
}

async function generateDesignImage({ style, roomImageDataUrl }) {
  const prompt = `You are an expert interior designer.
Redesign the room shown in the provided image in a ${style} style.
Requirements:
- Keep realistic geometry and room structure from the source photo.
- Replace decor, color palette, furniture, and textures to match ${style}.
- Produce a high quality photorealistic result.
- Do not add text, logos, or watermarks.`;

  const response = await fetch("https://api.openai.com/v1/images/generations", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${openAiKey}`
    },
    body: JSON.stringify({
      model: "gpt-image-1",
      prompt,
      image: roomImageDataUrl,
      size: "1024x1024"
    })
  });

  const data = await response.json();

  if (!response.ok) {
    throw new Error(data?.error?.message || "OpenAI request failed");
  }

  const imageBase64 = data?.data?.[0]?.b64_json;
  if (!imageBase64) {
    throw new Error("No image generated by OpenAI.");
  }

  return {
    style,
    prompt,
    imageUrl: `data:image/png;base64,${imageBase64}`
  };
}

async function serveStatic(pathname, res) {
  const safePath = pathname === "/" ? "/index.html" : pathname;
  const filePath = join(publicDir, safePath);

  if (!filePath.startsWith(publicDir)) {
    sendJson(res, 403, { error: "Forbidden" });
    return;
  }

  try {
    const file = await readFile(filePath);
    const ext = extname(filePath).toLowerCase();
    const type = MIME_TYPES[ext] || "application/octet-stream";
    res.writeHead(200, { "Content-Type": type });
    res.end(file);
  } catch {
    sendJson(res, 404, { error: "Not Found" });
  }
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url || "/", `http://${req.headers.host}`);

  if (req.method === "GET" && url.pathname === "/api/health") {
    return sendJson(res, 200, { ok: true, aiConfigured: Boolean(openAiKey) });
  }

  if (req.method === "POST" && url.pathname === "/api/designs") {
    try {
      const body = await parseJsonBody(req);
      const stylesRaw = body.styles || "Modern, Scandinavian, Minimalist";
      const roomImageDataUrl = body.roomImageDataUrl;
      const numDesigns = Number(body.numDesigns || 3);

      if (!roomImageDataUrl || !roomImageDataUrl.startsWith("data:image/")) {
        return sendJson(res, 400, { error: "Please upload a valid room image." });
      }

      const selectedStyles = String(stylesRaw)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean)
        .slice(0, Math.max(1, Math.min(numDesigns, 6)));

      if (!openAiKey) {
        return sendJson(res, 200, {
          warning: "OPENAI_API_KEY is not configured. Showing demo placeholders only.",
          designs: selectedStyles.map((style, idx) => ({
            style,
            prompt: `Redesign this room in ${style} style with cohesive furniture and warm lighting.`,
            imageUrl: `https://picsum.photos/seed/interior-${encodeURIComponent(style)}-${idx}/1024/768`
          }))
        });
      }

      const designs = [];
      for (const style of selectedStyles) {
        // Sequential calls keep rate-limiting simpler for an MVP.
        // eslint-disable-next-line no-await-in-loop
        designs.push(await generateDesignImage({ style, roomImageDataUrl }));
      }

      return sendJson(res, 200, { designs });
    } catch (error) {
      return sendJson(res, 500, {
        error: "Failed to generate designs. Verify your API key and try again.",
        details: error?.message || "Unknown error"
      });
    }
  }

  if (req.method === "GET") {
    return serveStatic(url.pathname, res);
  }

  return sendJson(res, 405, { error: "Method Not Allowed" });
});

server.listen(port, () => {
  console.log(`AIIInterior running at http://localhost:${port}`);
});
